[env:nanorp2040connect]
platform = raspberrypi
board = nanorp2040connect
framework = arduino

; Serial Monitor Settings
monitor_speed = 115200
monitor_filters = time, default

; Library Dependencies
lib_deps =
    arduino-libraries/WiFiNINA @ ^1.8.14
    mikalhart/TinyGPSPlus @ ^1.0.3
    arduino-libraries/Arduino_LSM6DSOX @ ^1.1.2

; Build Optimization Flags
build_flags = 
    -O2
    -D CORE_DEBUG_LEVEL=0
